services:
  backend:
    image: mindtrace-backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    pull_policy: never
    container_name: mindtrace-backend-dev
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/pkg/mod
    environment:
      - DB_DRIVER=sqlite
      - DB_DSN=mindtrace.db
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8080:8080"

  frontend:
    image: mindtrace-frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    pull_policy: never
    container_name: mindtrace-frontend-dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
      - "5173:5173"
    depends_on:
      - backend
